version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: dependency-check
      - dependency-name: uuid
      - dependency-name: standard
      - dependency-name: typescript
      - dependency-name: hallmark
      - dependency-name: "@voxpelli/tsconfig"
      - dependency-name: "@babel/preset-env"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
